###
# @name 현재 로그인한 사용자 정보
//GET http://localhost:8080/api/users/me
GET https://api.planit.com/api/users/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
# @name 비밀번호 변경
PATCH http://localhost:8080/api/users/me/password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

# sarita.veum / 123456
{
  "oldPassword": "rfof3ujoz",
  "newPassword": "123456"
}

###
# @name 사용자 정보 변경
PUT http://localhost:8080/api/users/me/update-profile
Content-Type: application/json
Authorization: Bearer {{auth_token}}


{
  "nickname": "{{$random.superhero.name}}"
}